name: publish Node.js Package to gpr

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    env:
      npm_token: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.npm_token != '' }}

      - uses: actions/setup-node@v4
        if: ${{ env.npm_token != '' }}
        with:
          node-version-file: './.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ env.npm_token != '' }}

      - run: npm publish --provenance --access public
        if: ${{ env.npm_token != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.npm_token }}

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@verkstedt'
      - run: npm ci

      - run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
