name: Publish to NPM and GitHub registries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        # Note: We can’t move this `if` to the job, because
        #       accessing secrets inside `if` is not allowed.
        if: ${{ env.NPM_TOKEN != '' || env.GITHUB_TOKEN != '' }}

      - uses: actions/setup-node@v4
        if: ${{ env.NPM_TOKEN != '' || env.GITHUB_TOKEN != '' }}
        with:
          node-version-file: './.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          scope: '@verkstedt'

      - run: npm ci
        if: ${{ env.NPM_TOKEN != '' || env.GITHUB_TOKEN != '' }}

      - name: 'Publish to NPM registry'
        if: ${{ env.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          npm publish \
            --registry=https://registry.npmjs.org \
            --provenance \
            --access=public

      - name: 'Switch Node.js to GitHub registry'
        if: ${{ env.GITHUB_TOKEN != '' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@verkstedt'

      - name: 'Publish to GitHub registry'
        if: ${{ env.GITHUB_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          npm publish \
            --registry=https://npm.pkg.github.com \
            --access public
